name: CI/CD

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21'
      - run: npm ci
      - run: npm run test
      - run: npm run build